//! Closed vocabularies. One variant per game model class. Growing these is
//! the main way the sim's scope grows.

/// `Models/Cards/<Name>.cs`. The Ironclad pool, plus the statuses, curses,
/// and tokens the Ironclad slice can meet.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum CardId {
    // Ironclad pool (Models/CardPools/IroncladCardPool.cs), multiplayer-only
    // cards (DemonicShield, Tank) excluded.
    Aggression,
    Anger,
    Armaments,
    AshenStrike,
    Barricade,
    Bash,
    BattleTrance,
    Bloodletting,
    BloodWall,
    Bludgeon,
    BodySlam,
    Brand,
    Break,
    Breakthrough,
    Bully,
    BurningPact,
    Cascade,
    Cinder,
    Colossus,
    Conflagration,
    Corruption,
    CrimsonMantle,
    Cruelty,
    DarkEmbrace,
    DefendIronclad,
    DemonForm,
    Dismantle,
    Dominate,
    DrumOfBattle,
    EvilEye,
    ExpectAFight,
    Feed,
    FeelNoPain,
    FiendFire,
    FightMe,
    FlameBarrier,
    ForgottenRitual,
    Havoc,
    Headbutt,
    Hellraiser,
    Hemokinesis,
    HowlFromBeyond,
    Impervious,
    InfernalBlade,
    Inferno,
    Inflame,
    IronWave,
    Juggernaut,
    Juggling,
    Mangle,
    MoltenFist,
    NotYet,
    Offering,
    OneTwoPunch,
    PactsEnd,
    PerfectedStrike,
    Pillage,
    PommelStrike,
    PrimalForce,
    Pyre,
    Rage,
    Rampage,
    Rupture,
    SecondWind,
    SetupStrike,
    ShrugItOff,
    Spite,
    Stampede,
    Stoke,
    Stomp,
    StoneArmor,
    StrikeIronclad,
    SwordBoomerang,
    Taunt,
    TearAsunder,
    Thrash,
    Thunderclap,
    Tremble,
    TrueGrit,
    TwinStrike,
    Unmovable,
    Unrelenting,
    Uppercut,
    Vicious,
    Whirlwind,
    // Statuses (Models/CardPools/StatusCardPool.cs), the act 1 subset.
    Wound,
    Slimed,
    Dazed,
    Burn,
    // Curses.
    AscendersBane,
    // Tokens.
    GiantRock,
}

/// `Models/Powers/<Name>Power.cs`.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum PowerId {
    Strength,
    Dexterity,
    Vulnerable,
    Weak,
    Frail,
    /// Byrdonis's Ritual. Grants Strength at end of its side's turn.
    Territorial,
    // Ironclad card powers.
    Aggression,
    NoDraw,
    Barricade,
    Colossus,
    Corruption,
    CrimsonMantle,
    Cruelty,
    DarkEmbrace,
    DemonForm,
    FeelNoPain,
    FlameBarrier,
    Hellraiser,
    Inferno,
    Juggernaut,
    Juggling,
    /// `TemporaryStrengthPower` with `IsPositive => false` (Mangle).
    Mangle,
    NoEnergyGain,
    OneTwoPunch,
    Pyre,
    Rage,
    Rupture,
    /// `TemporaryStrengthPower`, positive (Setup Strike).
    SetupStrike,
    Stampede,
    Plating,
    FreeAttack,
    Vicious,
    Unmovable,
}

/// `Models/Monsters/<Name>.cs`.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum MonsterId {
    Nibbit,
}
