//! Closed vocabularies. One variant per game model class. Growing these is
//! the main way the sim's scope grows.

/// `Models/Cards/<Name>.cs`. The Ironclad pool, plus the statuses, curses,
/// and tokens the Ironclad slice can meet.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum CardId {
    // Ironclad pool (Models/CardPools/IroncladCardPool.cs), multiplayer-only
    // cards (DemonicShield, Tank) excluded.
    Aggression,
    Anger,
    Armaments,
    AshenStrike,
    Barricade,
    Bash,
    BattleTrance,
    Bloodletting,
    BloodWall,
    Bludgeon,
    BodySlam,
    Brand,
    Break,
    Breakthrough,
    Bully,
    BurningPact,
    Cascade,
    Cinder,
    Colossus,
    Conflagration,
    Corruption,
    CrimsonMantle,
    Cruelty,
    DarkEmbrace,
    DefendIronclad,
    DemonForm,
    Dismantle,
    Dominate,
    DrumOfBattle,
    EvilEye,
    ExpectAFight,
    Feed,
    FeelNoPain,
    FiendFire,
    FightMe,
    FlameBarrier,
    ForgottenRitual,
    Havoc,
    Headbutt,
    Hellraiser,
    Hemokinesis,
    HowlFromBeyond,
    Impervious,
    InfernalBlade,
    Inferno,
    Inflame,
    IronWave,
    Juggernaut,
    Juggling,
    Mangle,
    MoltenFist,
    NotYet,
    Offering,
    OneTwoPunch,
    PactsEnd,
    PerfectedStrike,
    Pillage,
    PommelStrike,
    PrimalForce,
    Pyre,
    Rage,
    Rampage,
    Rupture,
    SecondWind,
    SetupStrike,
    ShrugItOff,
    Spite,
    Stampede,
    Stoke,
    Stomp,
    StoneArmor,
    StrikeIronclad,
    SwordBoomerang,
    Taunt,
    TearAsunder,
    Thrash,
    Thunderclap,
    Tremble,
    TrueGrit,
    TwinStrike,
    Unmovable,
    Unrelenting,
    Uppercut,
    Vicious,
    Whirlwind,
    // Statuses (Models/CardPools/StatusCardPool.cs), the act 1 subset.
    Wound,
    Slimed,
    Dazed,
    Burn,
    Infection,
    // Curses.
    AscendersBane,
    // Tokens.
    GiantRock,
    // Colorless (Models/CardPools/ColorlessCardPool.cs), as met in recordings.
    MindBlast,
}

/// `Models/Powers/<Name>Power.cs`.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum PowerId {
    Strength,
    Dexterity,
    Vulnerable,
    Weak,
    Frail,
    /// Byrdonis's Ritual. Grants Strength at end of its side's turn.
    Territorial,
    // Ironclad card powers.
    Aggression,
    NoDraw,
    Barricade,
    Colossus,
    Corruption,
    CrimsonMantle,
    Cruelty,
    DarkEmbrace,
    DemonForm,
    FeelNoPain,
    FlameBarrier,
    Hellraiser,
    Inferno,
    Juggernaut,
    Juggling,
    /// `TemporaryStrengthPower` with `IsPositive => false` (Mangle).
    Mangle,
    NoEnergyGain,
    OneTwoPunch,
    Pyre,
    Rage,
    Rupture,
    /// `TemporaryStrengthPower`, positive (Setup Strike).
    SetupStrike,
    Stampede,
    Plating,
    FreeAttack,
    Vicious,
    Unmovable,
    // Monster-side powers used in act 1.
    /// Caps HP loss at 1 per hit, one charge per hit (Vantom, Inklet).
    Slippery,
    /// Attacks cost 1 more this turn (Vine Shambler).
    Tangled,
    /// Damage taken grows 10% per card played this turn (Bygone Effigy).
    Slow,
    /// Player deals 30% less; `-1` amount means permanent (Shrinker Beetle).
    Shrink,
    /// Only the first card each turn may be played (Ceremonial Beast).
    Ringing,
    /// Stunned and stripped of Strength when HP drops to the amount.
    Plow,
    /// Secondary enemy: its death does not end combat.
    Minion,
    /// On death, spawns four Wrigglers (Phrog Parasite).
    Infested,
    /// Secondary enemy that revives to full HP the turn after dying.
    Illusion,
    /// HP loss at the end of the owner's turn (Slithering Strangler).
    Constrict,
    /// Negates the next debuff (Cubex Construct).
    Artifact,
    // Relic powers.
    /// Damage back to attackers (Bronze Scales).
    Thorns,
    /// Next attack card deals extra damage, then it is spent (Akabeko).
    Vigor,
    /// Block when block is cleared next turn (Self-Forming Clay).
    SelfFormingClay,
    // Potion powers.
    /// Heal at the end of the owner's turn, then decrement (Regen Potion).
    Regen,
    /// Next attack card deals triple damage (Gigantification Potion).
    Gigantification,
    /// Next card is played twice; gone at end of turn (Duplicator).
    Duplication,
    /// Negates the next HP loss (Lucky Tonic).
    Buffer,
    /// Draw one extra card per turn, decrementing (Clarity).
    Clarity,
    /// Unblockable HP loss at the end of the owner's turn (Powdered Demise).
    Demise,
    /// Energy after each energy reset, decrementing (Radiant Tincture).
    Radiance,
    /// Strength at the end of the owner's turn (Mazaleth's Gift).
    Ritual,
    /// Hand is not discarded at end of turn (Stable Serum).
    RetainHand,
    /// Block once block is cleared next turn (Ship in a Bottle).
    BlockNextTurn,
    /// `TemporaryStrengthPower` from Flex Potion.
    FlexPotion,
    /// `TemporaryStrengthPower`, negative, from Shackling Potion.
    ShacklingPotion,
    /// `TemporaryDexterityPower` from Speed Potion.
    SpeedPotion,
}

/// `Models/Monsters/<Name>.cs`.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum MonsterId {
    Nibbit,
    FuzzyWurmCrawler,
    ShrinkerBeetle,
    LeafSlimeS,
    LeafSlimeM,
    TwigSlimeS,
    TwigSlimeM,
    Inklet,
    Mawler,
    Fogmog,
    EyeWithTeeth,
    Flyconid,
    SnappingJaxfruit,
    SlitheringStrangler,
    VineShambler,
    CubexConstruct,
    AxeRubyRaider,
    AssassinRubyRaider,
    BruteRubyRaider,
    CrossbowRubyRaider,
    TrackerRubyRaider,
    Byrdonis,
    BygoneEffigy,
    PhrogParasite,
    Wriggler,
    Vantom,
    CeremonialBeast,
    KinFollower,
    KinPriest,
}

/// Every variant, for id lookups by name.
pub const ALL_CARDS: &[CardId] = &[
    CardId::Aggression,
    CardId::Anger,
    CardId::Armaments,
    CardId::AshenStrike,
    CardId::Barricade,
    CardId::Bash,
    CardId::BattleTrance,
    CardId::Bloodletting,
    CardId::BloodWall,
    CardId::Bludgeon,
    CardId::BodySlam,
    CardId::Brand,
    CardId::Break,
    CardId::Breakthrough,
    CardId::Bully,
    CardId::BurningPact,
    CardId::Cascade,
    CardId::Cinder,
    CardId::Colossus,
    CardId::Conflagration,
    CardId::Corruption,
    CardId::CrimsonMantle,
    CardId::Cruelty,
    CardId::DarkEmbrace,
    CardId::DefendIronclad,
    CardId::DemonForm,
    CardId::Dismantle,
    CardId::Dominate,
    CardId::DrumOfBattle,
    CardId::EvilEye,
    CardId::ExpectAFight,
    CardId::Feed,
    CardId::FeelNoPain,
    CardId::FiendFire,
    CardId::FightMe,
    CardId::FlameBarrier,
    CardId::ForgottenRitual,
    CardId::Havoc,
    CardId::Headbutt,
    CardId::Hellraiser,
    CardId::Hemokinesis,
    CardId::HowlFromBeyond,
    CardId::Impervious,
    CardId::InfernalBlade,
    CardId::Inferno,
    CardId::Inflame,
    CardId::IronWave,
    CardId::Juggernaut,
    CardId::Juggling,
    CardId::Mangle,
    CardId::MoltenFist,
    CardId::NotYet,
    CardId::Offering,
    CardId::OneTwoPunch,
    CardId::PactsEnd,
    CardId::PerfectedStrike,
    CardId::Pillage,
    CardId::PommelStrike,
    CardId::PrimalForce,
    CardId::Pyre,
    CardId::Rage,
    CardId::Rampage,
    CardId::Rupture,
    CardId::SecondWind,
    CardId::SetupStrike,
    CardId::ShrugItOff,
    CardId::Spite,
    CardId::Stampede,
    CardId::Stoke,
    CardId::Stomp,
    CardId::StoneArmor,
    CardId::StrikeIronclad,
    CardId::SwordBoomerang,
    CardId::Taunt,
    CardId::TearAsunder,
    CardId::Thrash,
    CardId::Thunderclap,
    CardId::Tremble,
    CardId::TrueGrit,
    CardId::TwinStrike,
    CardId::Unmovable,
    CardId::Unrelenting,
    CardId::Uppercut,
    CardId::Vicious,
    CardId::Whirlwind,
    CardId::Wound,
    CardId::Slimed,
    CardId::Dazed,
    CardId::Burn,
    CardId::Infection,
    CardId::AscendersBane,
    CardId::GiantRock,
    CardId::MindBlast,
];

pub const ALL_POWERS: &[PowerId] = &[
    PowerId::Strength,
    PowerId::Dexterity,
    PowerId::Vulnerable,
    PowerId::Weak,
    PowerId::Frail,
    PowerId::Territorial,
    PowerId::Aggression,
    PowerId::NoDraw,
    PowerId::Barricade,
    PowerId::Colossus,
    PowerId::Corruption,
    PowerId::CrimsonMantle,
    PowerId::Cruelty,
    PowerId::DarkEmbrace,
    PowerId::DemonForm,
    PowerId::FeelNoPain,
    PowerId::FlameBarrier,
    PowerId::Hellraiser,
    PowerId::Inferno,
    PowerId::Juggernaut,
    PowerId::Juggling,
    PowerId::Mangle,
    PowerId::NoEnergyGain,
    PowerId::OneTwoPunch,
    PowerId::Pyre,
    PowerId::Rage,
    PowerId::Rupture,
    PowerId::SetupStrike,
    PowerId::Stampede,
    PowerId::Plating,
    PowerId::FreeAttack,
    PowerId::Vicious,
    PowerId::Unmovable,
    PowerId::Slippery,
    PowerId::Tangled,
    PowerId::Slow,
    PowerId::Shrink,
    PowerId::Ringing,
    PowerId::Plow,
    PowerId::Minion,
    PowerId::Infested,
    PowerId::Illusion,
    PowerId::Constrict,
    PowerId::Artifact,
    PowerId::Thorns,
    PowerId::Vigor,
    PowerId::SelfFormingClay,
    PowerId::Regen,
    PowerId::Gigantification,
    PowerId::Duplication,
    PowerId::Buffer,
    PowerId::Clarity,
    PowerId::Demise,
    PowerId::Radiance,
    PowerId::Ritual,
    PowerId::RetainHand,
    PowerId::BlockNextTurn,
    PowerId::FlexPotion,
    PowerId::ShacklingPotion,
    PowerId::SpeedPotion,
];

pub const ALL_MONSTERS: &[MonsterId] = &[
    MonsterId::Nibbit,
    MonsterId::FuzzyWurmCrawler,
    MonsterId::ShrinkerBeetle,
    MonsterId::LeafSlimeS,
    MonsterId::LeafSlimeM,
    MonsterId::TwigSlimeS,
    MonsterId::TwigSlimeM,
    MonsterId::Inklet,
    MonsterId::Mawler,
    MonsterId::Fogmog,
    MonsterId::EyeWithTeeth,
    MonsterId::Flyconid,
    MonsterId::SnappingJaxfruit,
    MonsterId::SlitheringStrangler,
    MonsterId::VineShambler,
    MonsterId::CubexConstruct,
    MonsterId::AxeRubyRaider,
    MonsterId::AssassinRubyRaider,
    MonsterId::BruteRubyRaider,
    MonsterId::CrossbowRubyRaider,
    MonsterId::TrackerRubyRaider,
    MonsterId::Byrdonis,
    MonsterId::BygoneEffigy,
    MonsterId::PhrogParasite,
    MonsterId::Wriggler,
    MonsterId::Vantom,
    MonsterId::CeremonialBeast,
    MonsterId::KinFollower,
    MonsterId::KinPriest,
];
